name: first workflow
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: print welcome message 
        run: echo "welcome to our first workflow / github actions work" 
      - name: check out repository
        uses: actions/checkout@v5.0.0
      - name: list repo files
        run: ls -la
